# Generated by Django 5.1.7 on 2025-03-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="expiry_at",
        ),
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.CharField(max_length=4),
        ),
    ]
